### PR TITLE
Reference setup

### PR DESCRIPTION
**Pull request by jogold**

### CODE REVIEW

**Comment by jogold** [comment]
@markusl looks like there's an issue with the Docker volume not correctly being mounted when running in the GitHub action

**Comment by markusl** [comment]
@jogold what would be the preferred config for a case where the Lambda function consists of multiple .ts files?

**Comment by jogold** [comment]
> @jogold what would be the preferred config for a case where the Lambda function consists of multiple .ts files?

The construct will automatically bundle all your files and dependencies. You just point to the correct entry file (the one containing your `handler`) or name the file containing your `handler` with the construct's id as suffix (like I did here). In your handler's code can require/import from wherever you like.

**Comment by markusl** [comment]
@jogold now, if I run the command `npx projen && chmod 755 package.json && yarn install && yarn build` on macOS I will receive an error:
```
 FAIL  test/index.test.ts (35.101 s)tory, stat '/asset-input/cdk-ecr-image-scan-handler/lambda-handler/handler.ts'
  ✕ Create EcrImageScanResultHandler (33799 ms)

  ● Create EcrImageScanResultHandler

    Failed to bundle asset testing-stack/ecr-scan-result-handler/handler/Code/Stage: Error: docker exited with status 1
```

Is there a configuration error or am I misusing the API somehow?

**Comment by jogold** [comment]
Looks like a problem with Docker on macOS. I'm in the process of finalizing a way out of Docker for `aws-lambda-nodejs`: see https://github.com/aws/aws-cdk/pull/9632. It should work in your environment I think.

What I don't understand is that you didn't have any problems with v1.57.0?

**Pull request merged**
