### PR TITLE
Relative entry

### PR DESCRIPTION
**Pull request by jogold**

### CODE REVIEW

**Comment by jogold** [comment]
This is a temporary fix, this should be improved in the CDK

**Comment by jogold** [comment]
@markusl just to let you know that this temporary workaround is not need anymore now that https://github.com/aws/aws-cdk/pull/11729 is released.

**Comment by markusl** [comment]
Thanks @jogold ! This seems to be working now :)

**Comment by markusl** [comment]
@jogold unfortunately it still does not work. The following error is received when I try to use the module in another project:

`Cannot find entry file at project/node_modules/cdk-ecr-image-scan-handler/lib/teams.handler.ts`

Any ideas what is the problem?

**Comment by jogold** [comment]
> Any ideas what is the problem?

Yes, you need to completely remove the `entry` prop so that the construct will look it up based on the id: `email.ts` with a `NodejsFunction` with `id` `handler` will look for `email.handler.ts` or `email.handler.js` automatically. 

Automatic entry finding has been fixed for your use case in aws/aws-cdk#11729 but if you specify entry it is taken as-is.

**Pull request merged**
